df=read.csv("C:/Users/emily/Downloads/AirPassengers.csv")
head(df)
View(df)
tsData = ts(df$X.Passengers, start = c(1949,1), frequency = 12)
plot(tsData)
components.ts = decompose(tsData)
plot(components.ts)
library(tseries)
adf.test(na.omit(components.ts$random))
tsstationary = diff(na.omit(components.ts$random), differences = 1)
plot(tsstationary)
adf.test(tsstationary)
acf(tsstationary, lag.max = 34)
pacf(tsstationary, lag.max = 34)
fitARIMA <- arima(na.omit(components.ts$random), order = c(1,1,1),method = "ML")
library(lmtest)
coeftest(fitARIMA)
acf(fitARIMA$residuals)
pacf(fitARIMA$residuals)
library(forecast)
final=auto.arima(tsData, trace=TRUE)
forecast1 = forecast(final)
forecast1
